### ISSUE TITLE
Example revoke token?

### ISSUE THREAD

**Issue by paradoxfm** [appleboy/gin-jwt#143]
How impliment  revoke token method?
Where i can call it?

**Comment by andriisoldatenko** [comment]
@paradoxfm Could you please explain yourself?
in JWT you can't do it, it's "client side sessions", which means you can revoke all tokens changing private key, or change may be username/or any user data which inside JWT.
best

**Comment by paradoxfm** [comment]
@andriisoldatenko I want revoke custom token
because i have on token for one client, but client has many entering points

**Comment by tomriddle1234** [comment]
This function is necessary as many mature api service like firebase has the revoke feature.

I think it is possible to create a blacklist table of revoked tokens in memory. Maybe use a periodical check to release records in the table if expiration time reached.

So we can check if token already in blacklist each time received request, if so, return a 401 and make client login again, to get a new token.

**Comment by buildscientist** [comment]
@paradoxfm 
I don't think gin-jwt should be responsible for revoking tokens. That seems to be outside of the scope of this library given the complexity in implementation details. 

Even if the expiry of the token was kept in memory - what happens when you have multiple Gin services running? How are you going to share state between them? You'll need to roll something using Redis or similar. 

That said - I do believe GinJwtMiddleWare should accept a callback function that can revoke tokens.
