### ISSUE TITLE
`go get` fails with a build error

### ISSUE THREAD

**Issue by agubarev** [appleboy/gin-jwt#230]
go get -v -u gopkg.in/appleboy/gin-jwt.v2

```
get "gopkg.in/appleboy/gin-jwt.v2": found meta tag get.metaImport{Prefix:"gopkg.in/appleboy/gin-jwt.v2", VCS:"git", RepoRoot:"https://gopkg.in/appleboy/gin-jwt.v2"} at //gopkg.in/appleboy/gin-jwt.v2?go-get=1
gopkg.in/appleboy/gin-jwt.v2 (download)
github.com/dgrijalva/jwt-go (download)
github.com/gin-gonic/gin (download)
github.com/gin-contrib/sse (download)
github.com/go-playground/validator (download)
github.com/go-playground/universal-translator (download)
github.com/go-playground/locales (download)
github.com/leodido/go-urn (download)
github.com/golang/protobuf (download)
github.com/ugorji/go (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/mattn/go-isatty (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
gopkg.in/appleboy/gin-jwt.v2
# gopkg.in/appleboy/gin-jwt.v2
../../../gopkg.in/appleboy/gin-jwt.v2/auth_jwt.go:457:14: not enough arguments in call to c.SetCookie
	have (string, string, int, string, string, bool, bool)
	want (string, string, int, string, string, http.SameSite, bool, bool)
../../../gopkg.in/appleboy/gin-jwt.v2/auth_jwt.go:475:14: not enough arguments in call to c.SetCookie
	have (string, string, number, string, string, bool, bool)
	want (string, string, int, string, string, http.SameSite, bool, bool)
../../../gopkg.in/appleboy/gin-jwt.v2/auth_jwt.go:540:14: not enough arguments in call to c.SetCookie
	have (string, string, int, string, string, bool, bool)
	want (string, string, int, string, string, http.SameSite, bool, bool)
```

**Comment by bipinktr** [comment]
> not enough arguments in call to c.SetCookie

Same issue here as well, the issue was not there couple of days back, but now the issue is coming when trying to build.
`# github.com/appleboy/gin-jwt
/go/src/github.com/appleboy/gin-jwt/auth_jwt.go:457:14: not enough arguments in call to c.SetCookie
        have (string, string, int, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)
/go/src/github.com/appleboy/gin-jwt/auth_jwt.go:475:14: not enough arguments in call to c.SetCookie
        have (string, string, number, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)
/go/src/github.com/appleboy/gin-jwt/auth_jwt.go:540:14: not enough arguments in call to c.SetCookie
        have (string, string, int, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)`

**Comment by agubarev** [comment]
@bipinktr yes, same; it's strange because I first got this error yesterday, although the last commit which affected SetCookie() was on the 20th of November.

https://github.com/appleboy/gin-jwt/commit/d59ede46f6477186c4c2ff7e65d9f889e1e525ad

**Comment by bipinktr** [comment]
@agubarev I have solved the issue by implementing go modules [https://blog.golang.org/using-go-modules](https://blog.golang.org/using-go-modules) .

**Comment by agubarev** [comment]
@bipinktr yes, same, I posted just to notify. thanks for sharing.

**Comment by prernapreeti964** [comment]
I have not used modules and imported this directly in the code as below:
`package controller

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"strings"
	"time"
	jwt "github.com/appleboy/gin-jwt"
    )`

My CI pipeline is breaking because of the same error in building:
`Step 26/34 : RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -ldflags="-w -s" -o main
 ---> Running in a691f9029876
# github.com/appleboy/gin-jwt
../src/github.com/appleboy/gin-jwt/auth_jwt.go:457:14: not enough arguments in call to c.SetCookie
        have (string, string, int, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)
../src/github.com/appleboy/gin-jwt/auth_jwt.go:475:14: not enough arguments in call to c.SetCookie
        have (string, string, number, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)
../src/github.com/appleboy/gin-jwt/auth_jwt.go:540:14: not enough arguments in call to c.SetCookie
        have (string, string, int, string, string, bool, bool)
        want (string, string, int, string, string, http.SameSite, bool, bool)`

Can someone help resolve this?

**Comment by ovalverde** [comment]
This is happening due to change on method spec in go-gin https://github.com/gin-gonic/gin/commit/07c0f05f244589ff4a02320a01ad0a1fc102cbd5

To fixed this i upgraded my project to use mod as stated above. It is also important that if you   are migrating from a no go mod project you should also update your import path to be github.com/appleboy/gin-jwt/v2

**Comment by agubarev** [comment]
@ovalverde thanks for your response.

**Comment by appleboy** [comment]
@agubarev any other problem?

**Comment by kjozic** [comment]
I use modules but I have the same problem.

The problem is that gin (version 1.6.1) has a prototype `SetCookie (name, value string, maxAge int, path, domain string, sameSite http.SameSite, secure, httpOnly bool)` and gin-jwt (version 2.6.3) calls function as `SetCookie (mw.CookieName, tokenString, maxage, "/" mw.CookieDomain, mw.SecureCookie, mw.CookieHTTPOnly, )`.

So, the function call is missing the parameter `sameSite http.SameSite`.

**Comment by appleboy** [comment]
@kjozic I will take it.

**Comment by PhantomX7** [comment]
@appleboy is there any estimation time for this feature to be fixed?

**Comment by kjozic** [comment]
As a temporary fix, you can downgrade gin to a version v1.5.0 in your go.mod file:
```
require (
	github.com/appleboy/gin-jwt/v2 v2.6.3
	github.com/gin-contrib/cors v1.3.1
	github.com/gin-gonic/gin v1.5.0
        ...
)
```

Don't forget to download a specific version (`go get github.com/gin-gonic/gin@v1.5.0`).

**Comment by appleboy** [comment]
gin-jwt only support gin v1.5 not upgrade to v1.6 now.

**Comment by appleboy** [comment]
duplicated of #232
